services:
  nginx:
    image: nginx:alpine
    container_name: tabaratomano-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./scraper-errors:/usr/share/nginx/html/scraper-errors
    depends_on:
      - api
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  certbot-etc:
  certbot-var: