server {
    listen 80;
    server_name api.tabaratomano.com.br;

    # ROTA DO CERTBOT (ESSENCIAL)
    location /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
    }

    # SUA API
    location / {
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}