name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/tabaratomano-api

            echo "Atualizando código..."
            git pull origin main

            echo "Rebuild containers..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

            echo "Limpando imagens antigas..."
            docker system prune -f